include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    cascade_invocations: false
    directives_ordering: false
    sort_pub_dependencies: false
